name: desilike_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - cython
  - pandas
  - matplotlib
  - ipykernel
  - jupyterlab
  - astropy
  - pyfftw
  - fftw
  - openmpi
  - mpi4py
  - gcc_linux-64        # compilador C/C++
  - gxx_linux-64
  - gfortran_linux-64   # necesario para compilar CLASS (pyclass)
  - libblas
  - liblapack
  - pkg-config
  - make
  - git
  - getdist
  - anesthetic
  - tabulate
  - emcee
  - emcee  # conda-forge
  - iminuit
  - zeus-mcmc
  - pip:
      # instalamos los repositorios git con pip en el paso post-create
      - pip>=23.0
